/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/core/AppButton.vue')['default']
    FamilyIllustrated: typeof import('./components/FamilyIllustrated.vue')['default']
    FamilyMemberItem: typeof import('./components/FamilyMemberItem.vue')['default']
    FamilyMembersList: typeof import('./components/FamilyMembersList.vue')['default']
    FamilyTimeline: typeof import('./components/FamilyTimeline.vue')['default']
    Footer: typeof import('./components/core/Footer.vue')['default']
    Friends: typeof import('./components/Friends.vue')['default']
    GoalTracker: typeof import('./components/GoalTracker.vue')['default']
    Header: typeof import('./components/core/Header.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    IconDivider: typeof import('./components/IconDivider.vue')['default']
    IllustratedContent: typeof import('./components/IllustratedContent.vue')['default']
    MediaList: typeof import('./components/MediaList.vue')['default']
    Possibilities: typeof import('./components/Possibilities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportList: typeof import('./components/SupportList.vue')['default']
    Treatment: typeof import('./components/Treatment.vue')['default']
  }
}
